name: github pages
 
on:
  push:
    branches:
      - zqianhui  # 只有在该分支发生push事件时触发

# 工作流
jobs:
  deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 下载node，高于dumi规定的node版本即可
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 打包代码
      - name: Build Project
        run: |
          npm install      
          npm run build

       # 部署到GitHub
      - name: Deploy to Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist # 打包后存放的文件
